// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIac2J5uC0YYh3WvRNxeJWhrcsi3ZmI2k',
    appId: '1:833154955499:web:52d86238a185dd0da926ae',
    messagingSenderId: '833154955499',
    projectId: 'lavapiano',
    authDomain: 'lavapiano.firebaseapp.com',
    storageBucket: 'lavapiano.appspot.com',
    measurementId: 'G-PJCQZT70NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-HTHVndgtrxyC7m7pPPiGoGh5Oe8nWc',
    appId: '1:833154955499:android:dcf7e9fd1658afc8a926ae',
    messagingSenderId: '833154955499',
    projectId: 'lavapiano',
    storageBucket: 'lavapiano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe4HaSlypv9VCvywsMf2fcJFGkwDHKHPA',
    appId: '1:833154955499:ios:9de39c01edc33232a926ae',
    messagingSenderId: '833154955499',
    projectId: 'lavapiano',
    storageBucket: 'lavapiano.appspot.com',
    iosBundleId: 'com.example.laVapiano',
  );
}
